# Generated by Django 5.0.4 on 2024-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('confirm_address', models.TextField()),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh')], max_length=2)),
                ('languages', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada')], max_length=10)),
            ],
        ),
    ]
